### ISSUE TITLE
Run server listening on randomly-assigned port Error Autograder

### ISSUE THREAD

**Issue by Ysaid1** [comp426-2022-spring/a01-Ysaid1#3]
So, I seem to be getting this error from the autograder "Run server listening on randomly-assigned port", but can't figure out what it's from. I've tried to commit several changes, and have rechecked that it is indeed running on Port 3000, but still getting that error. Any tips on how to fix this?

**Comment by jdmar3** [comment]
That is not a you error, it is an autograder error. It should be fixed now. I have all checks working on a working example now.
